### ISSUE TITLE
cookie required

### ISSUE THREAD

**Issue by jamesli2021** [withastro/studio-issues#10] opened 2024-03-12 16:53 UTC
After connect to GitHub.

```
{"message":"\"githubOauthReturnTo\" cookie is required"}
```

**Comment by Princesseuh** [comment] 2024-03-12 16:53
Duplicate of https://github.com/withastro/studio-issues/issues/8

**Comment by matthewp** [comment] 2024-03-12 16:53
Thanks, which browser are you using?

**Closed** 2024-03-12 16:54 UTC

**Comment by matthewp** [comment] 2024-03-12 16:57
Were you using incognito mode by any chance?

**Comment by jamesli2021** [comment] 2024-03-12 19:25
I use safari and firefox on macOS, not incognito mode.
